#server:
#  port: 9090
#spring:
#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InniDBDialect